#!/usr/bin/env sh

# bsp, stack or float
yabai -m config layout bsp

yabai -m config window_placement second_child

# padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# mouse settings
yabai -m config mouse_follows_focus on

yabai -m config mouse_modifier alt
# left click + drag
yabai -m config mouse_action1 move
# right click + drag
yabai -m config mouse_action2 resize

yabai -m mouse_drop_action swap

# setup spaces
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 6)'); do
  yabai -m space --destroy 7
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 terminal
setup_space 2 web/notes
setup_space 3 media

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

# space 1: terminal
yabai -m rule --add app="iTerm" space=^1

# space 2: web and notes
yabai -m rule --add app="Chrome" space=^2
yabai -m rule --add app="Quip" space=^2

# space 3: chat and mail
yabai -m rule --add app="Slack" space=^3
yabai -m rule --add app="^Amazon Chime$" space=^3
yabai -m rule --add app="^Microsoft Outlook$" space=^3 
